### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by Oletus** [gkjohnson/webgl-gpu-power-estimation#18]
I'd be interested in using this repo, and possibly contributing, but the code doesn't have a license attached to it. Do you have some license in mind?

**Comment by Oletus** [comment]
Immediately after posting I noticed that the package.json file does mention MIT, but it'd be clearer if the license file was included.

**Comment by gkjohnson** [comment]
Hi @oletus! Thanks for your interest.

Including "MIT" in the package.json was actually a copy-paste error -- I've now removed it. I haven't added a license for this project at the moment.

One reason is because I think the big thing that's interesting about this project is the catalog of GPU data which has been scraped from videocardbenchmark.net, techpowerup.com, and notebookcheck.net -- I don't feel I have the authority to distribute that data under any kind of open license or give people the impression that it can use it freely without understanding where it came from. This was really just intended as an experiment and I've included the database as a means to provide a demo but otherwise I haven't used this in any professional capacity.

I guess what it comes down to is I wasn't sure what to do so I haven't included a license. If you have any thoughts or can point to a project that depends on scraped data of a similar form I'd be happy to hear it. I suppose one approach could be to just provide the logic in `src/index.js` and `src/utils.js` and leave it up to any consuming party to provide their own catalog of gpu information attained through a means they feel appropriate. Admittedly that logic is less interesting or unique but I think it matches GPU names pretty well which is worthwhile.

**Comment by Oletus** [comment]
Ok, thanks for clearing up the incorrect license information in the package.json. I understand that using the scraped data is a bit iffy. I see a couple of alternatives for that - using or making a simple OSS benchmark and collecting information ourselves, or switching to a public data source if something like that exists. Wikipedia came to mind but it seems like it uses copyleft type of license - I wonder if that still leaves the door open to using the data from there inside a larger program? Not a lawyer. Could also ask if any of the scraped sites would be okay with this kind of use of their data.

If you can just put the scripts under MIT that would already be valuable though.

**Comment by gkjohnson** [comment]
I might be able to do that and just be very explicit in the README that the data is not included in the license. I'll want to rearrange a couple things to make that more clear.

> using or making a simple OSS benchmark and collecting information ourselves, or switching to a public data source if something like that exists. Wikipedia came to mind but it seems like it uses copyleft type of license

I looked around for other sources of data and the benchmark websites seem to be the best because they provide a "performance" score which is useful for scaling graphics features or binning hardware into a high, medium, or low category. Trying to do anything with the specific values for clock speed or memory seems like it'd be pretty finicky. I suppose you could generate a guess at a performance value based on some of the GPU hardware data, though.

> Could also ask if any of the scraped sites would be okay with this kind of use of their data.

Yeah I haven't had to use this for anything real so I haven't gone out of my way to. If you wind up asking them for your use I'd be interested to hear what they say.

> If you can just put the scripts under MIT that would already be valuable though.

Are you just referring to the `index.js` and `utils.js` files under `/src` or the scraping scripts under `/scripts`, as well?

And just for my own interest what kind of app are you looking to use this for? I'm always glad to see people take interest in what I've put together.

**Comment by Oletus** [comment]
I think we'd get a reasonable performance estimate based on the single-precision FLOPS value that the manufacturer has reported. Wikipedia lists these for most NVIDIA and AMD GPUs and contains a formula for calculating it for Intel GPUs.

I'd say that license of index.js and utils.js is most important, since those would be integrated to the application, but it wouldn't hurt if the scraping scripts were MIT licensed as well.

**Comment by pboyer** [comment]
Hey @gkjohnson! Long time, no see. This is for Higharc. :) We basically just want to bin users based on perf tiers for our product and this looked like an interesting approach. Using this project is still exploratory for us, but using the scraping scripts might be a way for us to do comparisons (eg if we take the wikipedia data source approach, how close does the FLOPS number come to the benchmarking data?).

**Comment by gkjohnson** [comment]
Hey @pboyer! Thanks for the info. Glad to see this is interesting to you guys. Comparing one of the hardware values to see if it acts as any kind of consistent indicator for performance seems like a good idea.

I think right now I feel most comfortable licensing the `index.js` and `utils.js` files -- hopefully that's enough to experiment and get started? My plates a bit full at the moment so it may take a week or so for me to get around to reorganizing the repo but I'll let you know when I have chance.

Hope you guys are staying safe through everything!

**Comment by gkjohnson** [comment]
I've finished a bit of reorganizing and added a `LICENSE` file to the `src` directory as well as some clarifying wording to the README. Let me know if that suits what you guys are looking for!

**Comment by Oletus** [comment]
This helps for sure, the name matching script is useful. Thanks!

**Comment by gkjohnson** [comment]
Great! I'll close this for now but feel free to make another issue if you need something changed. And let me know if you guys find any other good sources of GPU data or wind up reaching out to sites I've used in this project.
