### ISSUE TITLE
Can't distinguish perf MHz MB on iphone6sp

### ISSUE THREAD

**Issue by gonnavis** [gkjohnson/webgl-gpu-power-estimation#24]
![image](https://user-images.githubusercontent.com/10785634/98229939-852f7480-1f95-11eb-95b6-c2162dbaaf7c.png)

**Comment by gkjohnson** [comment]
Yes we are limited by what data is available in the GPU benchmark websites the data gets sampled from. In this case you can see what's available for the Apple A12X Bionic GPU on this site, which doesn't include MB or MHz information:

https://www.notebookcheck.net/Mobile-Graphics-Cards-Benchmark-List.844.0.html?

In this case the data is interpolated, as well, to get a consistent performance metric, which is why there are so many decimals. I'll plan to truncate the value in the UI like I do for the example data table below, as well.

**Comment by gonnavis** [comment]
Thanks!
